[package]
name = "rusty-tin-foil"
version = "0.1.0"
authors = ["Tommy Ryan <tommy@thetallboy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"